
services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  auth_service:
    build: ./auth_service
    container_name: auth_service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    env_file:
      - ./auth_service/.env
    networks:
      - backend

  book_service:
    build: ./book_service
    container_name: book_service
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
      - auth_service
    env_file:
      - ./book_service/.env
    networks:
      - backend

volumes:
  mongo_data:

networks:
  backend:
